---
title: "HW_9_Q4"
author: "Colin Frishberg"
output: pdf 
---

```{r}
library(tidyverse)
library(sandwich)
library(lmtest)
library(stargazer)
library(fec16)
library(patchwork)

```

```{r}
head(campaigns)

summary(campaigns$ttl_disb)

p1 <- ggplot(results_house, aes(x = general_percent)) +
  geom_histogram( aes(y=after_stat(density)),
                        col = "black",
                        fill = "darkblue") +
stat_function(fun = dnorm, args = list(mean = mean(results_house$general_percent, na.rm = TRUE), sd = sd(general_percent$results_house, na.rm = TRUE)), 
              col = "red")


p2 <- ggplot(campaigns, aes(x = ttl_disb)) +
  geom_histogram( aes(y = after_stat(density)),
                        col = "black",
                        fill = "darkblue") +
stat_function(fun = dnorm, args = list(mean = mean(campaigns$ttl_disb, na.rm = TRUE), sd = sd(campaigns$ttl_disb, na.rm = TRUE)),
              col = "red")

p1 + p2
```
```{r, include=FALSE}
df1 <- inner_join(results_house, campaigns, by = "cand_id")

nrow(df1)
ncol(df1)
```
#Q4.4

```{r}
unique(df1$party)

#general_votes = # of votes in the general election in this case for the house of representatives
#candidate_party = Democratic, Republican, Other
# ttl_disb = total_disbursements 

df1 <- df1 %>% 
  mutate(
    candidate_party = case_when(
      party == "REP" ~ "Republican",
      party =="DEM" ~ "Democrat",
      TRUE ~ "Other Party"
    )
  )

ggplot(df1, aes(x = ttl_disb, y = general_votes, colour = candidate_party)) + 
  geom_point() +
  scale_colour_manual(values = c("Democrat" = "blue",
                                 "Republican" = "red",
                                 "Other Party" = "darkgreen"),
                      name = "Party") +
  scale_x_continuous() +
  scale_y_continuous() +
  labs(title = "2016 House Campaign Disbursments and Candidate Votes",
       x = "Disbursements",
       y = "Votes")
  
   

```

